# Generated by Django 5.0.1 on 2024-02-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_info', models.TextField(verbose_name='Thread Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='numberplate.licenseplate', verbose_name='License Plate')),
            ],
            options={
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.CreateModel(
            name='ThreadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='numberplate.thread', verbose_name='Thread')),
            ],
        ),
        migrations.CreateModel(
            name='TrespassingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_trespassing', models.DateTimeField(verbose_name='Datetime of Trespassing')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trespassing_events', to='numberplate.licenseplate', verbose_name='License Plate')),
            ],
            options={
                'verbose_name_plural': 'Trespassing Events',
            },
        ),
    ]
