# Generated by Django 5.0.1 on 2024-02-11 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('access_token_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Access Token ID')),
                ('access_token', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Access Token')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Address ID')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street_name', models.CharField(max_length=255, verbose_name='Street Name')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street Number')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Deal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('step_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Step ID')),
                ('name_of_step', models.CharField(max_length=100, verbose_name='Name of Step')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('authority_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Authority ID')),
                ('name', models.CharField(max_length=255, verbose_name='Authority Name')),
                ('authority_iban', models.CharField(max_length=255, verbose_name='IBAN')),
                ('authority_bic', models.CharField(max_length=255, verbose_name='BIC')),
                ('authority_pipedrive_id', models.CharField(max_length=255, verbose_name='Pipedrive ID')),
                ('authority_address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='authorities_address', to='numberplate.address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Contact ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('company_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Company Name')),
                ('address', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='numberplate.address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='LicencePlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_plates', to='numberplate.deal', verbose_name='License Plate')),
                ('responsible_authorities', models.ManyToManyField(to='numberplate.authorities', verbose_name='Responsible Authorities')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_info', models.TextField(verbose_name='Thread Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='numberplate.deal', verbose_name='License Plate')),
            ],
            options={
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.CreateModel(
            name='ThreadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='numberplate.thread', verbose_name='Thread')),
            ],
        ),
        migrations.CreateModel(
            name='TrespassingEvent',
            fields=[
                ('trespassing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Trespassing ID')),
                ('trespassing_event', models.CharField(max_length=255, verbose_name='Trespassing Event')),
                ('datetime_of_trespassing', models.DateTimeField(verbose_name='Datetime of Trespassing')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('trespassing_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Trespassing Datetime')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trespassing_events', to='numberplate.deal', verbose_name='Deal')),
            ],
            options={
                'verbose_name_plural': 'Trespassing Events',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='plate_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_deals', to='numberplate.trespassingevent', verbose_name='Trespassing Event'),
        ),
        migrations.CreateModel(
            name='TrespassingLocation',
            fields=[
                ('trespassing_location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Trespassing Location ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('doc_poa_lawyer_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='POA Lawyer ID')),
                ('doc_poa_kkr_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='POA KKR ID')),
                ('doc_kkr_order_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='KKR Order ID')),
                ('location_shortname', models.CharField(blank=True, default=None, max_length=32, unique=True)),
                ('location_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='numberplate.address', verbose_name='Location Address')),
                ('location_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numberplate.contact', verbose_name='Location Owner')),
            ],
        ),
        migrations.AddField(
            model_name='trespassingevent',
            name='trespassing_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numberplate.trespassinglocation', verbose_name='Trespassing Location'),
        ),
        migrations.AddField(
            model_name='deal',
            name='trespassing_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numberplate.trespassinglocation', verbose_name='Trespassing Location'),
        ),
        migrations.AddField(
            model_name='deal',
            name='workflow_step',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='numberplate.workflowstep', verbose_name='Workflow Step'),
        ),
    ]
