# Generated by Django 5.0.1 on 2024-02-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0001_initial'),
    ]

    operations = [
    ]
