# Generated by Django 5.0.2 on 2024-02-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0002_remove_deal_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trespassinglocation',
            name='customer_name',
        ),
    ]
