# Generated by Django 5.0.1 on 2024-02-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0002_auto_20240206_1721'),
    ]

    operations = [
    ]
