# Generated by Django 5.0.1 on 2024-02-06 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0003_auto_20240206_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesstokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Activation key')),
            ],
        ),
    ]
