# Generated by Django 5.0.2 on 2024-02-18 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0003_remove_trespassinglocation_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Lawyer ID')),
                ('lawyer_name', models.CharField(max_length=255, unique=True, verbose_name='Lawyer Name')),
                ('lawyer_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numberplate.contact', verbose_name='Lawyer Contact')),
            ],
            options={
                'verbose_name_plural': 'Lawyers',
            },
        ),
    ]
