# Generated by Django 5.0.1 on 2024-02-06 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0004_accesstokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstokens',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstokens',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
