# Generated by Django 5.0.2 on 2024-02-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0004_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lawyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='numberplate.lawyer', verbose_name='Lawyer Contact'),
        ),
    ]
