# Generated by Django 5.0.1 on 2024-02-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplate', '0006_accesstoken_delete_accesstokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='trespassingevent',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
    ]
